name: "Easy Remote Access (FRP Client)"
version: "1.0.2" 
slug: "frp_client"
description: "Securely access your Home Assistant from anywhere using a private FRP tunnel."
url: "https://github.com/razvan11-cloud/frp-addon" 
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
init: false
startup: "application"
boot: "auto"

options:
  server_address: ""
  auth_token: ""
  unique_id: ""

schema:
  server_address: "str"
  auth_token: "password"
  unique_id: "str"
