# Add-on metadata
name: "Easy Remote Access (FRP Client)"
version: "1.0.0"
slug: "frp_client"
description: "Securely access your Home Assistant from anywhere using a private FRP tunnel."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: "application"
boot: "auto"

# Configuration options shown to the user
options:
  unique_id: "" # This will be the box where the user enters their key

# Schema for validating user input
schema:
  unique_id: "str"