name: "Easy Remote Access (FRP Client)"
version: "1.0.1" # Bump the version
slug: "frp_client"
description: "Securely access your Home Assistant from anywhere using a private FRP tunnel."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i368
init: false
startup: "application"
boot: "auto"

# --- NEW CONFIGURATION SECTION ---
options:
  server_address: ""
  auth_token: ""
  unique_id: ""

schema:
  server_address: "str"
  auth_token: "str" # Can also use "password" type
  unique_id: "str"